################################################################
# Traefik logs configuration
################################################################
log:
  # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  level: WARN

experimental:
  plugins:
    sablier:
      moduleName: "github.com/acouvreur/sablier"
      version: "v1.2.0"

global:
  checkNewVersion: true
  sendAnonymousUsage: true
################################################################
# Access logs configuration
################################################################
accessLog:
  filePath: /log/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - 200
      - 300-302
      - 400-499
    retryAttempts: true
    minDuration: 10ms
################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: :8080
################################################################
# Providers
################################################################
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: false
    network: traf-external
    defaultRule: "Host(`{{ .Name }}.{{ index .Labels \"com.docker.compose.service\"}}.dev.local`)"
  file:
    directory: /configurations/
    watch: true
    debugLogGeneratedTemplate: true
################################################################
# SSL Resolvers
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: admin
      storage: /etc/acme/acme.json
      tlsChallenge: true
      caserver: https://ca.dev.local:9000/acme/acme/directory
      # httpChallenge:
      #   entryPoint: web
      # dnsChallenge: true


################################################################
################################################################
#
# OLD CONFIG
#
################################################################
################################################################



# ################################################################
# # EntryPoints configuration
# ################################################################
#
# # EntryPoints definition
# #
# # Optional
# #
# entryPoints:
#   web:
#     address: :80
#     http:
#         redirections:
#           entrypoint:
#             to: websecure
#             scheme: https
#
#   websecure:
#     address: :443
#
#   metrics:
#     address: :8082
#
# ################################################################
# # Provider configuration
# ################################################################
# providers:
#   ################################################################
#   # Docker configuration backend
#   ################################################################
#   # Enable Docker configuration backend
#   docker:
#     # Docker server endpoint. Can be a tcp or a unix socket endpoint.
#     #
#     # Required
#     # Default: "unix:///var/run/docker.sock"
#     #
#     # endpoint: tcp://10.10.10.10:2375
#     endpoint: "unix:///var/run/docker.sock"
#
#     # Default host rule.
#     #
#     # Optional
#     # Default: "Host(`{{ normalize .Name }}`)"
#     #
#     # defaultRule:
#       # Host(`{{ normalize .Name }}.localhost`)
#
#       # Expose containers by default in traefik
#       #
#       # Optional
#       # Default: true
#       #
#     exposedByDefault: false
#     useBindPortIP: true
#     #  useBindPortIP: true
#     # tls:
#       # insecureSkipVerify: true
#
#   ################################################################
#   # File Provider
#   ################################################################
#   file:
#     directory: /etc/traefik/dynamic
#     watch: true
#
# ################################################################
# # Metrics configuration backend
# ################################################################
# metrics:
#   ################################################################
#   # Prometheus Metric Logging
#   ################################################################
#   # Enable Prometheus
#   #
#   # Optional
#   #
#   prometheus:
#     # Buckets for latency metrics
#     #
#     # Optional
#     # Default: "0.100000, 0.300000, 1.200000, 5.000000"
#     #
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5.0
#
#     # Enable metrics on entry points
#     #
#     # Optional
#     # Default: true
#     #
#     addEntryPointsLabels: true
#     # Enable metrics on routers
#     #
#     # Optional
#     # Default: true
#     #
#     addRoutersLabels: true
#     # Enable metrics on services
#     #
#     # Optional
#     # Default: true
#     #
#     addServicesLabels: true
#
#     # Entry point used to expose metrics
#     #
#     # Optional
#     # Default: "traefik"
#     entryPoint: metrics
#
#     # If manualRouting is true, it disables the default
#     # internal router in order to allow one to create
#     # a custom router for the prometheus@internal service.
#     #
#     # Optional
#     # Default: false
#   #  manualRouting: true
#
# # - --certificatesresolvers.letsResolve.acme.tlschallenge=true
# # - --certificatesresolvers.letsResolve.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
# # - --certificatesresolvers.letsResolve.acme.email=gospaceaus@gmail.com
# # - --certificatesresolvers.letsResolve.acme.storage=/acme.json
# #
# # - --certificatesresolvers.leresolver.acme.httpchallenge=true
# # - --certificatesresolvers.leresolver.acme.email=gospaceaus@gmail.com #Set your email address here, is for the generation of SSL certificates with Let's Encrypt.
# # - --certificatesresolvers.leresolver.acme.storage=./acmehttp.json
# # - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
# certificatesResolvers:
#   letsResolve:
#     acme:
#       email: fleming_hamish@yahoo.com
#       storage: /acme.json
#       caServer: https://acme-staging-v02.api.letsencrypt.org/directory
#       # caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       # tlsChallenge: {}
#       # dnsChallenge:
#       #   provider: digitalocean
#       #   delayBeforeCheck: 0
#       # httpChallenge:
#       # used during the challenge
#       # entryPoint: websecure
#       # entryPoint: web
#   # le:
#   #   acme:
#   #     httpChallenge:
#   #       # used during the challenge
#   #       entryPoint: http
#   #     email: abcd@outlook.com
#   #     storage: acme.json
#   #     # Use Let's Encrypt Staging CA when testing!
#   #     #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
#
# ################################################################
# # Traefik logs configuration
# ################################################################
#
# # Traefik logs
# # Enabled by default and log to stdout
# #
# # Optional
# #
# log:
#   # Log level
#   #
#   # Optional
#   # Default: "ERROR"
#   #
#   level: DEBUG
#
#   # Sets the filepath for the traefik log. If not specified, stdout will be used.
#   # Intermediate directories are created if necessary.
#   #
#   # Optional
#   # Default: os.Stdout
#   #
#   # filePath: log/traefik.log
#
#   # Format is either "json" or "common".
#   #
#   # Optional
#   # Default: "common"
#   #
#   # format: json
#
#
# ################################################################
# # Access logs configuration
# ################################################################
# # Enable access logs
# # By default it will write to stdout and produce logs in the textual
# # Common Log Format (CLF), extended with additional fields.
# #
# # Optional
# #
# # accessLog:
# #   # Sets the file path for the access log. If not specified, stdout will be used.
# #   # Intermediate directories are created if necessary.
# #   #
# #   # Optional
# #   # Default: os.Stdout
# #   #
# #   filePath: /path/to/log/log.txt
# #
# #   # Format is either "json" or "common".
# #   #
# #   # Optional
# #   # Default: "common"
# #   #
# #   format: json
#
#
#
# ################################################################
# # API and dashboard configuration
# ################################################################
#
# # Enable API and dashboard
# #
# # Optional
# #
# api:
#   # Enable the API in insecure mode
#   #
#   # Optional
#   # Default: false
#   #
#   insecure: true
#
#   # Enabled Dashboard
#   #
#   # Optional
#   # Default: true
#   #
#   dashboard: true
#
#   # Enabled Debug
#   #
#   # Optional
#   # Default: true
#   #
#   debug: true
#
# ################################################################
# # Ping configuration
# ################################################################
#
# # Enable ping
# ping:
#   # Name of the related entry point
#   #
#   # Optional
#   # Default: "traefik"
#   #
#   entryPoint: web
#   # If manualRouting is true, it disables the default
#   # internal router in order to allow one to create
#   # a custom router for the ping@internal service.
#   #
#   # Optional
#   # Default: false
#   # manualRouting: true
#
#
# ################################################################
# # API and dashboard configuration
# ################################################################
#
# # Enable API and dashboard
# #
# # Optional
# #
# api:
#   # Enable the API in insecure mode
#   #
#   # Optional
#   # Default: false
#   #
#   insecure: true
#
#   # Enabled Dashboard
#   #
#   # Optional
#   # Default: true
#   #
#   dashboard: true
#
#   # Enabled Debug
#   #
#   # Optional
#   # Default: true
#   #
#   debug: true
#
# ################################################################
# # Ping configuration
# ################################################################
#
# # Enable ping
# ping:
#   # Name of the related entry point
#   #
#   # Optional
#   # Default: "traefik"
#   #
#   entryPoint: web
#   # If manualRouting is true, it disables the default
#   # internal router in order to allow one to create
#   # a custom router for the ping@internal service.
#   #
#   # Optional
#   # Default: false
#   # manualRouting: true
